import {
    generateIncomeExpenseChart,
    generateExpenseBreakdownChart,
    generateGoalsProgressChart
} from "@/lib/charts";

export interface ReportData {
    userName: string;
    month: string;
    year: number;
    stats: {
        income: number;
        expense: number;
        balance: number;
    };
    allocations: Array<{
        name: string;
        amount: number;
        percentage: number;
        target: number;
    }>;
    categories: Array<{
        name: string;
        amount: number;
        type: "income" | "expense";
    }>;
    investments: Array<{
        name: string;
        type: string;
        value: number;
    }>;
    aiInsight: string;
    previousMonthStats?: {
        income: number;
        expense: number;
    };
    dailySpending?: Array<{ date: string; amount: number }>;
    expenseCategories?: Array<{ name: string; amount: number; color: string }>;
    goalsWithProgress?: Array<{ name: string; current: number; target: number; color: string }>;
}

const reportLabels = {
    id: {
        title: "MONEV WEALTH REPORT",
        totalIncome: "TOTAL PEMASUKAN",
        totalExpense: "TOTAL PENGELUARAN",
        balance: "SALDO BERSIH",
        allocations: "Alokasi 50/30/20",
        categories: "Category Alokasi",
        realized: "Realisasi (%)",
        target: "Target (%)",
        nominal: "Nominal",
        topExpenses: "Top Pengeluaran",
        category: "Kategori",
        amount: "Jumlah",
        portfolio: "Portofolio Investasi",
        asset: "Asset",
        type: "Tipe",
        marketValue: "Nilai Pasar",
        aiAdvice: "AI Smart Advice",
        footer: "Monev AI - Generated by Strategic Finance Engine.",
        page: "Halaman",
        userLabel: "Pelapor",
        printedOn: "Dicetak pada",
        incomeVsExpense: "Pemasukan vs Pengeluaran",
        expenseBreakdown: "Rincian Pengeluaran",
        goalsProgress: "Progress Tabungan",
        dailySpendingTrend: "Trend Pengeluaran Harian"
    },
    en: {
        title: "MONEV WEALTH REPORT",
        totalIncome: "TOTAL INCOME",
        totalExpense: "TOTAL EXPENSE",
        balance: "NET BALANCE",
        allocations: "50/30/20 Allocation",
        categories: "Category",
        realized: "Actual (%)",
        target: "Target (%)",
        nominal: "Amount",
        topExpenses: "Top Expenses",
        category: "Category",
        amount: "Amount",
        portfolio: "Investment Portfolio",
        asset: "Asset",
        type: "Type",
        marketValue: "Market Value",
        aiAdvice: "AI Smart Advice",
        footer: "Monev AI - Generated by Strategic Finance Engine.",
        page: "Page",
        userLabel: "User",
        printedOn: "Printed on",
        incomeVsExpense: "Income vs Expense",
        expenseBreakdown: "Expense Breakdown",
        goalsProgress: "Goals Progress",
        dailySpendingTrend: "Daily Spending Trend"
    }
};

export async function generateWealthReport(data: ReportData, locale: "id" | "en" = "id") {
    const { default: jsPDF } = await import("jspdf");
    const { default: autoTable } = await import("jspdf-autotable");

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const labels = reportLabels[locale];

    const dateLocale = locale === "id" ? "id-ID" : "en-US";

    const formatCurrency = (val: number) => {
        return new Intl.NumberFormat("id-ID", {
            style: "currency",
            currency: "IDR",
            minimumFractionDigits: 0,
        }).format(val);
    };

    const incomeExpenseChart = await generateIncomeExpenseChart(
        { income: data.stats.income, expense: data.stats.expense },
        data.previousMonthStats || { income: 0, expense: 0 },
        locale
    );

    const expenseBreakdownChart = data.expenseCategories 
        ? await generateExpenseBreakdownChart(data.expenseCategories, locale)
        : null;

    const goalsProgressChart = data.goalsWithProgress
        ? await generateGoalsProgressChart(data.goalsWithProgress, locale)
        : null;

    doc.setFillColor(14, 165, 233); // sky-500
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(labels.title, margin, 25);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`${data.month} ${data.year}`, pageWidth - margin - 30, 25);

    // User Info
    doc.setTextColor(51, 65, 85); // slate-700
    doc.setFontSize(12);
    doc.text(`${labels.userLabel}: ${data.userName}`, margin, 55);
    doc.text(`${labels.printedOn}: ${new Date().toLocaleDateString(dateLocale)}`, margin, 62);

    // Summary Box
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.roundedRect(margin, 75, pageWidth - (margin * 2), 35, 3, 3);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(labels.totalIncome, margin + 10, 85);
    doc.text(labels.totalExpense, margin + 75, 85);
    doc.text(labels.balance, margin + 140, 85);

    doc.setFontSize(12);
    doc.setTextColor(51, 65, 85);
    doc.text(formatCurrency(data.stats.income), margin + 10, 95);
    doc.text(formatCurrency(data.stats.expense), margin + 75, 95);

    doc.setTextColor(14, 165, 233);
    doc.setFont("helvetica", "bold");
    doc.text(formatCurrency(data.stats.balance), margin + 140, 95);

    doc.addPage();
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(labels.incomeVsExpense, margin, 25);
    
    const imgData1 = incomeExpenseChart.replace('data:image/png;base64,', '');
    doc.addImage(imgData1, 'PNG', margin, 35, pageWidth - (margin * 2), 200);

    if (expenseBreakdownChart) {
        doc.addPage();
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text(labels.expenseBreakdown, margin, 25);
        
        const imgData2 = expenseBreakdownChart.replace('data:image/png;base64,', '');
        doc.addImage(imgData2, 'PNG', margin, 35, pageWidth - (margin * 2), 200);
    }

    if (goalsProgressChart) {
        doc.addPage();
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text(labels.goalsProgress, margin, 25);
        
        const imgData3 = goalsProgressChart.replace('data:image/png;base64,', '');
        doc.addImage(imgData3, 'PNG', margin, 35, pageWidth - (margin * 2), 200);
    }

    doc.addPage();

    // 50/30/20 Rules
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(labels.allocations, margin, 130);

    autoTable(doc, {
        startY: 135,
        margin: { left: margin, right: margin },
        head: [[labels.categories, labels.realized, labels.target, labels.nominal]],
        body: data.allocations.map(a => [
            a.name,
            `${a.percentage.toFixed(1)}%`,
            `${a.target}%`,
            formatCurrency(a.amount)
        ]),
        headStyles: { fillColor: [14, 165, 233] },
        theme: "striped"
    });

    // Top Expenses
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const topExpensesStartY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
    doc.text(labels.topExpenses, margin, topExpensesStartY);

    autoTable(doc, {
        startY: topExpensesStartY + 20,
        margin: { left: margin, right: margin },
        head: [[labels.category, labels.amount]],
        body: data.categories
            .filter(c => c.type === "expense")
            .sort((a, b) => b.amount - a.amount)
            .slice(0, 5)
            .map(c => [c.name, formatCurrency(c.amount)]),
        headStyles: { fillColor: [244, 63, 94] }, // rose-500
        theme: "striped"
    });

    // Investments
    if (data.investments.length > 0) {
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        const investmentsStartY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
        doc.text(labels.portfolio, margin, investmentsStartY);

        autoTable(doc, {
            startY: investmentsStartY + 20,
            margin: { left: margin, right: margin },
            head: [[labels.asset, labels.type, labels.marketValue]],
            body: data.investments.map(i => [i.name, i.type, formatCurrency(i.value)]),
            headStyles: { fillColor: [16, 185, 129] }, // emerald-500
            theme: "striped"
        });
    }

    // AI Insight
    const lastY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
    if (lastY < 240) doc.addPage();

    const currentY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15 < 240 ? 25 : lastY;

    doc.setFillColor(248, 250, 252); // slate-50
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 40, 2, 2, "FD");

    doc.setFontSize(12);
    doc.setTextColor(14, 165, 233);
    doc.setFont("helvetica", "bold");
    doc.text(labels.aiAdvice, margin + 5, currentY + 10);

    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // slate-600
    doc.setFont("helvetica", "normal");

    const splitText = doc.splitTextToSize(data.aiInsight, pageWidth - (margin * 2) - 10);
    doc.text(splitText, margin + 5, currentY + 20);

    // Footer
    const totalPages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(
            `${labels.footer} ${labels.page} ${i} dari ${totalPages}`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: "center" }
        );
    }

    return doc;
}
