version: '3.8'

services:
  monev:
    container_name: monev-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=/app/data/sqlite.db
      - NODE_ENV=production
      - PORT=3000
      - PAKASIR_PROJECT=monev-app
      - PAKASIR_API_KEY=x734fXlpTu47VszlGU0eNTI4Tr6Pjpiz
    volumes:
      - monev-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monev.rule=Host(`monev.app`)"
      - "traefik.http.routers.monev.entrypoints=websecure"
      - "traefik.http.routers.monev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.monev-http.rule=Host(`monev.app`)"
      - "traefik.http.routers.monev-http.entrypoints=web"
      - "traefik.http.routers.monev-http.middlewares=redirect-to-https@file"
      - "traefik.http.services.monev.loadbalancer.server.port=3000"
    networks:
      - dokploy-network

volumes:
  monev-data:


networks:
  dokploy-network:
    external: true
