version: '3.8'

services:
  monev:
    container_name: monev-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=/app/data/sqlite.db
      - NODE_ENV=production
      - PORT=3000
      - PAKASIR_PROJECT=monev-app
      - PAKASIR_API_KEY=x734fXlpTu47VszlGU0eNTI4Tr6Pjpiz
      - VAPID_PUBLIC_KEY=BBBAcIn4QjsXxi9hAtHN9jBwJlXExp6dRn6rc9H9j12iYJAvHMRLx1TxNciVrt3GbA15uDnyQlXDbHQDgIDSQ8U
      - VAPID_PRIVATE_KEY=w10CmSQqNdhrTyDIo-t5mVYRqb2xjqjwW2b4TSrjP-s
    volumes:
      - monev-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monev.rule=Host(`monev.app`)"
      - "traefik.http.routers.monev.entrypoints=websecure"
      - "traefik.http.routers.monev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.monev-http.rule=Host(`monev.app`)"
      - "traefik.http.routers.monev-http.entrypoints=web"
      - "traefik.http.routers.monev-http.middlewares=redirect-to-https@file"
      - "traefik.http.services.monev.loadbalancer.server.port=3000"
    networks:
      - dokploy-network

volumes:
  monev-data:


networks:
  dokploy-network:
    external: true
